"""Create questions and documents tables

Revision ID: 31071ba7d1d9
Revises: 
Create Date: 2025-11-11 21:27:05.474577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31071ba7d1d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('filename', sa.String(length=200), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='文件访问URL'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型：pdf, docx, image等'),
    sa.Column('processing_status', sa.String(length=20), nullable=True, comment='处理状态：pending, processing, completed, failed'),
    sa.Column('total_questions', sa.Integer(), nullable=True, comment='提取的题目总数'),
    sa.Column('processed_questions', sa.Integer(), nullable=True, comment='已处理的题目数'),
    sa.Column('ocr_confidence_avg', sa.String(length=10), nullable=True, comment='平均OCR置信度'),
    sa.Column('extraction_errors', sa.JSON(), nullable=True, comment='提取错误信息'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False, comment='上传用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理完成时间'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False, comment='题目编号'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目主要内容'),
    sa.Column('full_content', sa.Text(), nullable=True, comment='题目完整内容（包括多行文本）'),
    sa.Column('question_type', sa.String(length=50), nullable=False, comment='题目类型：multiple_choice, fill_blank, true_false, essay, other'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True, comment='难度级别：easy, medium, hard'),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='学科分类：数学、语文、英语等'),
    sa.Column('topic_tags', sa.JSON(), nullable=True, comment='知识点标签，存储为JSON数组'),
    sa.Column('options', sa.JSON(), nullable=True, comment="选择题选项，JSON格式：[{label: 'A', content: '选项内容'}]"),
    sa.Column('correct_answer', sa.Text(), nullable=True, comment='正确答案'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='题目解析'),
    sa.Column('answer_key', sa.Text(), nullable=True, comment='答案详解'),
    sa.Column('source_image_path', sa.String(length=500), nullable=True, comment='来源图片路径'),
    sa.Column('source_image_url', sa.String(length=500), nullable=True, comment='来源图片URL（如果存储在云存储）'),
    sa.Column('source_document_id', sa.UUID(), nullable=True, comment='来源文档ID'),
    sa.Column('ocr_confidence', sa.String(length=10), nullable=True, comment='OCR识别置信度'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已人工验证'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('processing_status', sa.String(length=20), nullable=True, comment='处理状态：pending, processing, completed, failed'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建用户ID'),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='验证用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('documents')
    # ### end Alembic commands ###
